-- 插入中国和东南亚六个国家
INSERT INTO `draco`.`base__district`(`initial`, `level`, `cityCode`, `initials`, `center`, `suffix`, `createdAt`, `deletedAt`, `pinyin`, `mergerName`, `isDeleted`, `simpleName`, `name`, `id`, `order`, `updatedAt`, `DistrictParent`, `CreatedBy`, `UpdatedBy`) VALUES ('z', 'COUNTRY', NULL, 'zg', NULL, '国', now(), 0, 'zhong guo', '中国', 0, NULL, '中国', 'R000001', NULL, now(), NULL, NULL, NULL);
INSERT INTO `draco`.`base__district`(`initial`, `level`, `cityCode`, `initials`, `center`, `suffix`, `createdAt`, `deletedAt`, `pinyin`, `mergerName`, `isDeleted`, `simpleName`, `name`, `id`, `order`, `updatedAt`, `DistrictParent`, `CreatedBy`, `UpdatedBy`) VALUES ('x', 'COUNTRY', NULL, 'xjp', NULL, '国', now(), 0, 'xing jia po', '新加坡', 0, NULL, '新加坡', 'R536780', NULL, now(), NULL, NULL, NULL);
INSERT INTO `draco`.`base__district`(`initial`, `level`, `cityCode`, `initials`, `center`, `suffix`, `createdAt`, `deletedAt`, `pinyin`, `mergerName`, `isDeleted`, `simpleName`, `name`, `id`, `order`, `updatedAt`, `DistrictParent`, `CreatedBy`, `UpdatedBy`) VALUES ('f', 'COUNTRY', NULL, 'flb', NULL, '国', now(), 0, 'fei lv bin', '菲律宾', 0, NULL, '菲律宾', 'R443174', NULL, now(), NULL, NULL, NULL);
INSERT INTO `draco`.`base__district`(`initial`, `level`, `cityCode`, `initials`, `center`, `suffix`, `createdAt`, `deletedAt`, `pinyin`, `mergerName`, `isDeleted`, `simpleName`, `name`, `id`, `order`, `updatedAt`, `DistrictParent`, `CreatedBy`, `UpdatedBy`) VALUES ('y', 'COUNTRY', NULL, 'yn', NULL, '国', now(), 0, 'yue nan', '越南', 0, NULL, '越南', 'R49915', NULL, now(), NULL, NULL, NULL);
INSERT INTO `draco`.`base__district`(`initial`, `level`, `cityCode`, `initials`, `center`, `suffix`, `createdAt`, `deletedAt`, `pinyin`, `mergerName`, `isDeleted`, `simpleName`, `name`, `id`, `order`, `updatedAt`, `DistrictParent`, `CreatedBy`, `UpdatedBy`) VALUES ('m', 'COUNTRY', NULL, 'mlxy', NULL, '国', now(), 0, 'ma lai xi ya', '马来西亚', 0, NULL, '马来西亚', 'R2108121', NULL, now(), NULL, NULL, NULL);
INSERT INTO `draco`.`base__district`(`initial`, `level`, `cityCode`, `initials`, `center`, `suffix`, `createdAt`, `deletedAt`, `pinyin`, `mergerName`, `isDeleted`, `simpleName`, `name`, `id`, `order`, `updatedAt`, `DistrictParent`, `CreatedBy`, `UpdatedBy`) VALUES ('y', 'COUNTRY', NULL, 'ydlxy', NULL, '国', now(), 0, 'yin du li xi ya', '印度尼西亚', 0, NULL, '印度尼西亚', 'R304751', NULL, now(), NULL, NULL, NULL);
INSERT INTO `draco`.`base__district`(`initial`, `level`, `cityCode`, `initials`, `center`, `suffix`, `createdAt`, `deletedAt`, `pinyin`, `mergerName`, `isDeleted`, `simpleName`, `name`, `id`, `order`, `updatedAt`, `DistrictParent`, `CreatedBy`, `UpdatedBy`) VALUES ('t', 'COUNTRY', NULL, 'tg', NULL, '国', now(), 0, 'tai guo', '泰国', 0, NULL, '泰国', 'R2067731', NULL, now(), NULL, NULL, NULL);

-- 将中国省份的父id指向中国id
update  `base__district` set DistrictParent='R000001'  where level='PROVINCE'

--

